openapi: 3.0.3
info:
  title: BPMN Diagram
  description: Provide Business Process Modeling Notation (BPMN) diagrams
  version: 1.0.0
servers:
  - url: 'https://n35ro2ic4d.execute-api.eu-central-1.amazonaws.com/prod/engine-rest/process-definition/key/invoice/xml'
paths:
  /xml:
    get:
      description: Return business process modeling notation
      operationId: getBpmnDiagram
      responses:
        200:
          description: The BPMN diagram provided successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessProcessModel'
components:
  schemas:
    BusinessProcessModel:
      type: object
      required:
        - id
        - bpmn20Xml
      properties:
        id:
          type: string
        bpmn20Xml:
          type: string
